### ISSUE TITLE
[BUG] Mobs freeze

### ISSUE THREAD

**Issue by kangolist** [LoneDev6/Issues-ServerBooster#11]
**Describe the bug**
I have default config in ServerBooster and the monsters block and spawn a lot of mobs and increase the memory on the server excessively.

**Expected behavior**

**Screenshots**
Video:  https://drive.google.com/file/d/1vP9z_ESG0ihnl39f2tW3DriI2xNyifIN/view?usp=sharing

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: fabric 1.15.2
 - Plugin version: latest

**Comment by LoneDev6** [comment]
I cannot access the video, post it on youtube as unlisted video and send here the link.
Don't write "latest", tell me your plugin version.
Also do you have any report (for example timings report) or similar to prove that ram is increased?
Anyway the purpose of the plugin is to limit mob spawns to avoid useless server lag, you can customize these limits but the default ones will fit any normal survival server

**Comment by kangolist** [comment]
https://www.youtube.com/watch?v=fUFl25CIXmk and the memory grows with the frozen monsters.
