### ISSUE TITLE
[BUG]  1.16 block and items not detectable

### ISSUE THREAD

**Issue by OverBrave** [LoneDev6/Issues-ServerBooster#12]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47111280/86053632-73771700-ba61-11ea-8587-ef6583dc926c.png)
```
block-minecraft-warped_nylium: Çarpık Nesilyum
```
I put this string to lang file but keep gray color and not changed name.

![image](https://user-images.githubusercontent.com/47111280/86053652-796cf800-ba61-11ea-8693-5a6ecc1179c9.png)

Thats Normally

No error
Paper 24 1.16.1

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/Issues-ServerBooster/issues/13
