### ISSUE TITLE
[language problem] Can't Chinese

### ISSUE THREAD

**Issue by HoneyBearc** [LoneDev6/Issues-ServerBooster#13]
Version 1.0.33
15 / 16 items cannot be converted into Chinese
15 Chinese culture has not been repaired
http://secondheartbeat.idv.tw/a/1593524889335
http://secondheartbeat.idv.tw/a/123

**Comment by LoneDev6** [comment]
Thanks!
please download the file here: https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1.72184/update?update=345085

Let me know if works fine now

**Comment by HoneyBearc** [comment]
Language file changed Still the same 
Not working

**Comment by LoneDev6** [comment]
Download the .zip file not the plugin
![image](https://user-images.githubusercontent.com/27242001/86245931-85b09c80-bbaa-11ea-8524-59043a898062.png)
http://www.matteodev.it/spigot/holodrops/assets/lang.zip

**Comment by HoneyBearc** [comment]
http://secondheartbeat.idv.tw/a/bandicam%202020-07-01%2021-21-39-021

**Comment by LoneDev6** [comment]
I'm fixing this, thanks a lot

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/Issues-ServerBooster/issues/7
