### ISSUE TITLE
[BUG] Console errors

### ISSUE THREAD

**Issue by jmuirhead** [LoneDev6/Issues-ServerBooster#15]
**Describe the bug**
Console is spammed with errors when items are mined.

Pastebin link https://pastebin.com/JZNX0NLn

Main two errors
 [04:34:11] [Server thread/ERROR]: Could not pass event ItemMergeEvent to ServerBooster v1.0.34
java.lang.NullPointerException: null

[04:34:11] [Server thread/ERROR]: Could not pass event ItemSpawnEvent to ServerBooster v1.0.34
java.lang.NullPointerException: null

**Comment by LoneDev6** [comment]
Please post the error on pastebin, this is not readable at all.
Thanks

**Comment by jmuirhead** [comment]
> 
> 
> Please post the error on pastebin, this is not readable at all.
> Thanks

Here's the link https://pastebin.com/JZNX0NLn

**Comment by LoneDev6** [comment]
Thanks a lot, really strange.. did this happen again?
I think there was something strange on the server about dropped items, are you using another item stacker?

**Comment by jmuirhead** [comment]
It happens anytime multiple items get dropped, they don’t group together. The console is spammed nonstop with this error.

**Comment by LoneDev6** [comment]
Check if you have set config_holo.yml merge.hologram.format
Error seems to indicate that config_holo.yml doesn't contain these settings:
```YAML
  hologram:
    enabled: true
    format: "&f{name} &bx{amount}"
```

Or probably you don't have the holo language file, check if you set the lang in config_holo.yml and if you have the file inside lang folder.

**Comment by jmuirhead** [comment]
Yeah idk, i deleted the serverbooster folder ins \plugins\ and after the 4th time it stopped giving me the error. At least for now.
