### ISSUE TITLE
[BUG] "Tipped Arrows" and "Potions".

### ISSUE THREAD

**Issue by MeesterMaarten** [LoneDev6/Issues-ServerBooster#16]
All "Tipped Arrows" and "Potions" are not showing their correct name when being dropped and stacked on ground.

ServerBooster: 1.0.34
Paper-1.16.1: latest build-90 [Jul 12, 2020]

![unknown](https://user-images.githubusercontent.com/46909512/87350103-aa682500-c557-11ea-8d4b-ffe718d53068.png)

Thanks in advance for looking at this problem!
Sincerely, мααятєи' [ѕavarιa]#5173 - MeesterMaarten.

**Comment by MeesterMaarten** [comment]
It turns out that all "**Music Discs**" have this problem too!

**Comment by LoneDev6** [comment]
Thanks for the report, please replace your en_us.yml file with this: https://hasteb.in/aguzoluh.pl
