### ISSUE TITLE
[BUG] Potion lang problem

### ISSUE THREAD

**Issue by OverBrave** [LoneDev6/Issues-ServerBooster#17]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47111280/87537103-c4fae500-c6a2-11ea-92d9-cfc753aa0f20.png)

![image](https://user-images.githubusercontent.com/47111280/87537124-cd532000-c6a2-11ea-8e38-7fb027b8d51f.png)

ServerBooster - 1.0.36

**Comment by LoneDev6** [comment]
Delete the language file and restart, as specified in the update note
https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1.72184/update?update=348218

let me know

**Comment by OverBrave** [comment]
I already delete my language file. Its same.

**Comment by LoneDev6** [comment]
Updated to latest update?

I doubt, please delete the file, update and let me know

**Comment by LoneDev6** [comment]
Read here for more info:
https://github.com/LoneDev6/Issues-ServerBooster/issues/16#issuecomment-658151340

**Comment by OverBrave** [comment]
I changed all "." to "_" and problem fixed.
