### ISSUE TITLE
Items are being removed when chunks unload.

### ISSUE THREAD

**Issue by MeesterMaarten** [LoneDev6/Issues-ServerBooster#18]
Hello LoneDev,

I'm currently running ServerBooster: **1.0.40** on the latest Paper: **build-101**.

It seems that items are being removed when chunks are unloaded and this causes quite a few problems in my vanilla server.

Players are building vanilla spawners with water flows and minecarts with hoppers to collect these items, but it turns out that they are soon too far from the collector while standing in their AFK-spot.
The spawner chunks become unloaded and the items are instant removed!

It is also not possible for them to stand closer to the collector, because then they are loading unwanted cave chunks underground so that their spawner no longer works optimally. **Not easy, I understand that!**

Is there a way to solve this problem with ServerBooster? Something like a separate item removal such as **Clearlagg** or something in the settings that I can adjust? It all seems to work perfect in singleplayer and therefore players are getting a bit annoyed.

Thanks in advance!

Sincerely,
MeesterMaarten - мααятєи' [ѕavarιa]#5173

**Comment by LoneDev6** [comment]
Only way to fix this is to disable the chunk unloader or increase its value from 6000 to 72000 (1 hour).
Let me know
