### ISSUE TITLE
[BUG] java.lang.NoSuchFieldError: aware

### ISSUE THREAD

**Issue by kangolist** [LoneDev6/Issues-ServerBooster#19]
**Describe the bug**

**To Reproduce**
4. See error: https://pastebin.com/vtU8jz5R

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: fabric 1.15.2
 - Plugin version: 1.0.40

**Additional context**
I have this WARN on console, when I'm in spawn i dont have spam with this WARN in console, Only when I am surrounded by monsters then I receive this error, can you please help me with a solution?

**Comment by LoneDev6** [comment]
Make sure you're using the latest paper build https://papermc.io/downloads#Paper-1.15
