### ISSUE TITLE
[BUG] Holographic Displays aren't showing up

### ISSUE THREAD

**Issue by tyleraharrison** [LoneDev6/Issues-ServerBooster#20]
**Describe the bug**
Holographic Displays aren't showing up when items are dropped. The worlds are in config and config has been reloaded. Version is 1.16.1 Paper.

**To Reproduce**
1. Drop items

**Expected behavior**
Number to be displayed

**Info (please complete the following information):**
 - Server version: 1.16.1
 - Client version: Vanilla
 - Plugin version: 1.0.40

**Additional context**
Brand new install with worlds enabled

**Comment by tyleraharrison** [comment]
Bug was solved with a couple of restarts of the server. So weird

**Comment by LoneDev6** [comment]
I have no clue, maybe spigot bug? another plugin interfering?
anyway, send another message here if you encounter the same issue
