### ISSUE TITLE
[BUG] disappearing NPCs

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/Issues-ServerBooster#21]
**Describe the bug**
The NPC monster disappears on the server when using this plugin.

**To Reproduce**
1. Create NPC (for example baby zombie)
2. Wait for the SB to delete the NPC

**Expected behavior**
NPC Monsters will not disappear

**Screenshots**
![2020-08-06_21 03 34](https://user-images.githubusercontent.com/29830635/89571748-7f0be980-d828-11ea-8b62-bda9de51cf6c.png)
For example, this mob disappears if I do /npc reload to reappear.

**Info (please complete the following information):**
 - Server version: paper 1.16.1
 - Plugin version: 1.0.40

**Additional context**
I use Citizens on NPCs (https://ci.citizensnpcs.co/job/Citizens2/)

**Comment by LoneDev6** [comment]
Is it still happening?

**Comment by 100petr** [comment]
I'll try it and (probably) I'll let you know tomorrow. Thanks for your interest.

**Comment by 100petr** [comment]
Looks like it's not happening anymore. If it happens by accident, I will open the topic and try to provide some details.

**Comment by LoneDev6** [comment]
Thanks, I think it was a citizens 2 bug

**Comment by 100petr** [comment]
This NPC disappears again: / I'll try the server a day without SB to see if that's it.

**Comment by LoneDev6** [comment]
I find it really strange as if the entity has a custom name won't disappear

are you sure it's related to serverbooster?

**Comment by 100petr** [comment]
I think yes. SB Is not in server today and the NPC is there. If it is on the SB server, I can refresh the NPC several times a day (I don't know how long it will take to disappear)

**Comment by LoneDev6** [comment]
Sincerly I have no idea on how to fix this as I'm skipping deletion of entities with custom names, so it's strange that the plugin still removes them

**Comment by 100petr** [comment]
It is interesting that only one NPC disappears.

**Comment by LoneDev6** [comment]
Send a screenshot of the NPC

**Comment by 100petr** [comment]
![2020-09-14_17 30 54](https://user-images.githubusercontent.com/29830635/93106087-2265df00-f6b0-11ea-87f6-8c9a9c5ae9b1.png)

**Comment by LoneDev6** [comment]
Mmhhh.. I see nothing strange on this, the only thing is that this NPC is on a lilypad
Can you try moving it to a surface made of solid blocks? Let's see if it disappears

**Comment by 100petr** [comment]
Still 
![2020-09-15_16 25 51](https://user-images.githubusercontent.com/29830635/93223309-35d87f00-f770-11ea-8693-cefd260ef8db.png)
after /citizens reload
![2020-09-15_16 26 00](https://user-images.githubusercontent.com/29830635/93223314-37a24280-f770-11ea-8798-26cf2b69baec.png)

**Comment by 100petr** [comment]
Now I have looked at the place again and it is no longer there.

**Comment by LoneDev6** [comment]
I really have no idea, you may schedule a /citizens reload every 15 minutes in the meantime

Sorry for the inconveniences

**Comment by LoneDev6** [comment]
NOTE for me: I suspect that this problem is MAYBE (I have to check) NPCs are not of the correct entity type, they may be something else internally like slimes, armorstands or similar, so ServerBooster doesn't skip them

**Comment by LoneDev6** [comment]
Should be fixed in the new upcoming release
