### ISSUE TITLE
tps drop[BUG] 

### ISSUE THREAD

**Issue by Westloch** [LoneDev6/Issues-ServerBooster#23]
**Describe the bug**
recvently update to i.16.1 and this keeps showing up on console

17.08 17:51:33 [Server] ERROR Could not pass event ItemMergeEvent to ServerBooster v1.0.41
17.08 17:51:33 [Server] INFO java.lang.NullPointerException: null
17.08 17:51:33 [Server] ERROR Could not pass event ItemMergeEvent to ServerBooster v1.0.41
17.08 17:51:33 [Server] INFO java.lang.NullPointerException: null
17.08 17:51:33 [Server] ERROR Could not pass event ItemMergeEvent to ServerBooster v1.0.41
17.08 17:51:33 [Server] INFO java.lang.NullPointerException: null

theres no extra commands we are running, this happens while server booster runs in the background

**To Reproduce**

run server

**Expected behavior**

server tps drops drastically 

**Info (please complete the following information):**

 - Server version: 1.16.1
 - Plugin version: 1.0.41

**Comment by LoneDev6** [comment]
Delete language files and restart

**Comment by Westloch** [comment]
yep, seems to have fixed the issue, thanks!
