### ISSUE TITLE
[BUG] Item Names working wrongly in some cases

### ISSUE THREAD

**Issue by plebexer** [LoneDev6/Issues-ServerBooster#25]
hi!, some item names are not loading properly, i think i already reported this to you but i think its better to make an issue here
some of the items i noticed that are affected by this are Fireworks and Player Heads
im using the es_AR language
screenshot:
![image](https://user-images.githubusercontent.com/34526458/93954073-284c6780-fd23-11ea-81d3-5344210d17c0.png)

 - Server version: paper 1.15.2
 - Plugin version: 1.0.45

**Comment by LoneDev6** [comment]
Delete language file and restart
