### ISSUE TITLE
[BUG]  Visual mob freezing bug

### ISSUE THREAD

**Issue by Westloch** [LoneDev6/Issues-ServerBooster#6]
**Describe the bug**
Players have reported some mobs to be standing still as if afk/freezing in place, mobs do not de-spawn, players cannot hit or kill the mobs, mobs do not follow or track player. Everything is currently default, I have not changed anything in any config file. It seems to be a visual glitch because no one could see that “afk” mob, only the players experiencing the “bug”

**To Reproduce**
Don’t know exactly how to reproduce, it seems to affect players randomly.

**Info**
Server version: paper 1.15.2
 Plugin version:1.0.31

**Comment by plebexer** [comment]
i was going to report this, but i saw you also reported it, so yes, the same thing is happening to me, i think it happens when a mob is in a chunk that is unloaded and then you load it again.

**Comment by LoneDev6** [comment]
> 
> 
> i was going to report this, but i saw you also reported it, so yes, the same thing is happening to me, i think it happens when a mob is in a chunk that is unloaded and then you load it again.

Mmh.. interesting, is this happening only after the paper update? i fixed that bug since some old serverbooster versions, now it reappeared

**Comment by arturek1666** [comment]
The same issue is happening to me xD, I was going to report it into more details but looks like I don't have to anymore xD

**Comment by LoneDev6** [comment]
Daaaamn, well seems to be a spigot/paper update issue, any error in logs?

**Comment by arturek1666** [comment]
No saddly no errors and that's the problem

**Comment by arturek1666** [comment]
I did see some entity update for paper but not sure if that the issue

**Comment by arturek1666** [comment]
Maybe this ????
https://github.com/PaperMC/Paper/commit/b59052566bac09ce537a09b7995b5e42fe75b8de

Not sure but maybe

**Comment by arturek1666** [comment]
Will check the: 1.0.32 version and see if anything changed to better etc. Maybe mob freezing got fixed xD

**Comment by arturek1666** [comment]
yeah still freezing :(
![image](https://user-images.githubusercontent.com/1558228/83452011-d4ee9a80-a44f-11ea-9579-43031b795274.png)

**Comment by Westloch** [comment]
![image](https://user-images.githubusercontent.com/62856212/83461887-70bbde80-a42f-11ea-8ffd-d156984fa7c2.png)

This keeps showing up in console don’t know if it has to do with anything?

**Comment by arturek1666** [comment]
Strange I don't have nothing like you, but yes this error looks like it have issues with live entity

**Comment by LoneDev6** [comment]
Strange, well the only way for me to fix is to know which paper build actually introduced the bug, only with this information i can check their changelog and see which feature they edited, so i can try to bypass that problem.

thanks all

**Comment by arturek1666** [comment]
After some papermc updates looks like the issue is gone LOL

**Comment by Westloch** [comment]
I’ll run it for a couple hours today and see if players still report freezing mobs.

**Comment by Westloch** [comment]
i have tested the plugin for a few hours and the bug is still there but i figured out that its only when "config_optimize_entities.yml" is enabled. i have disabled this by setting the world names within that config to something other than my actual world name.

Without "config_optimize_entities.yml" everything works fine, When i enable "config_optimize_entities.yml" the mobs freeze


 
![image](https://user-images.githubusercontent.com/62856212/83959502-29748a00-a843-11ea-95fd-adffd5929716.png)

**Comment by plebexer** [comment]
the bug was fixed , some days ago with one paper update that came out, but now again in the lastest paper version mobs freeze again

**Comment by Honakura** [comment]
Yes same Problem
Minecraft Server Version >>> 1.15.2
Client Version >>> 1.15.2
Plugin Version >>> 1.0.32
PaperMC >>> paper-355.jar

**Comment by LoneDev6** [comment]
> 
> 
> the bug was fixed , some days ago with one paper update that came out, but now again in the lastest paper version mobs freeze again

Damn, so which version of paper was working fine? I have to read its code and check what they changed
