### ISSUE TITLE
[BUG] Freezing Mobs

### ISSUE THREAD

**Issue by Honakura** [LoneDev6/Issues-ServerBooster#8]
**Freezing Mobs**
I have the Problem/Bug when new Mobs are spawning they will be freezed and have no more brain.
I cannot hit them or they can hit me.
When i rejoin there are gone but when i will still play there will be still there and do nothing.

Here a screenshot
![image](https://user-images.githubusercontent.com/64560136/85203730-eec52400-b30f-11ea-98f0-881420805a45.png)

Server Infos:
Server Version >>> 1.15.2
Client Version >>> 1.15.2
Plugin Version >>> The latest xD :P  /// JOKE >>> 1.0.32 <<<

I hope you can help me the plugin is great.
Sry for my bad english!

**Comment by Honakura** [comment]
OH sry there is always a Bug report for this

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/Issues-ServerBooster/issues/6
no problem
