### ISSUE TITLE
[Suggestion] set limit to groups

### ISSUE THREAD

**Issue by Westloch** [LoneDev6/Issues-ServerBooster#9]
Ability to group mobs and set limits to that group instead of per mob.

**Comment by LoneDev6** [comment]
What do you mean?
The radius_max and chunk_max is a "group" based config

**Comment by Westloch** [comment]
after running a few tests, server booster seems to be working as intended. Thanks for the replay!

**Comment by LoneDev6** [comment]
No problem!
You can also use **/serverbooster mobs showradius** to show the radius around you
